#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh hq4x.ps.h /Tps_3_0 filters\hq4x.cg /Emain_fragment /VnPSHQ4x
//
//
// Parameters:
//
//   sampler2D $decal;
//   float k;
//   float lum_add;
//   float max_w;
//   float min_w;
//   float mx;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   mx           c0       1
//   k            c1       1
//   max_w        c2       1
//   min_w        c3       1
//   lum_add      c4       1
//   $decal       s0       1
//
//
// Default values:
//
//   mx
//     c0   = { 1, 0, 0, 0 };
//
//   k
//     c1   = { -1.1, 0, 0, 0 };
//
//   max_w
//     c2   = { 0.75, 0, 0, 0 };
//
//   min_w
//     c3   = { 0.03, 0, 0, 0 };
//
//   lum_add
//     c4   = { 0.33, 0, 0, 0 };
//

// Shader type: pixel 

xps_3_0
defconst $decal, sampler2d, object, [1, 1], s0
defconst k, float, scalar, [1, 1], c1, { -1.10000002, 0, 0, 0 }
defconst lum_add, float, scalar, [1, 1], c4, { 0.330000013, 0, 0, 0 }
defconst max_w, float, scalar, [1, 1], c2, { 0.75, 0, 0, 0 }
defconst min_w, float, scalar, [1, 1], c3, { 0.0299999993, 0, 0, 0 }
defconst mx, float, scalar, [1, 1], c0, { 1, 0, 0, 0 }
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=19
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0.xy
dcl_texcoord1 r1
dcl_texcoord2 r2
dcl_texcoord3 r3
dcl_texcoord4 r4
dcl_texcoord5 r5
dcl_texcoord6 r6

def c252, 0, 0, 0, 0
def c253, 0, 0, 0, 0
def c254, 0, 0, 0, 0
def c255, 1, 2, 0.00100000005, 0.125


    exec
    tfetch2D r7.xzy_, r1.zw, tf0
    tfetch2D r13.xzy_, r2.zw, tf0
    tfetch2D r11.xzy_, r3.zw, tf0
    tfetch2D r10.xzy_, r4.zw, tf0
    tfetch2D r9.xzy_, r1.xy, tf0
    tfetch2D r12.xzy_, r3.xy, tf0
    exec
    tfetch2D r8.xzy_, r2.xy, tf0
    tfetch2D r1.xzy_, r4.xy, tf0
    tfetch2D r14.xyz_, r5.zw, tf0
    tfetch2D r3.xyz_, r6.zw, tf0
    tfetch2D r5.xyz_, r5.xy, tf0
    tfetch2D r2.xyz_, r6.xy, tf0
    exec
    tfetch2D r0._xyz, r0.xy, tf0
    alloc colors
    exec
    add r15.xyz, r2.zyx, -r0.wzy
    add r16.xyz, r5.zyx, -r0.wzy
    add r17.xyz, r14.zyx, -r0.wzy
  + movs r0._, r3.z
    add r4.xyw, r8.yzx, -r1.yzx
  + adds_prev r6.x, -r0.w
    add r6.yzw, r9.yyzx, -r12.yyzx
  + movs r0._, r3.y
    dp3 r4.z, r6_abs.ywz, c255.x
  + adds_prev r6.y, -r0.z
    exec
    dp3 r4.w, r4_abs.xwy, c255.x
  + movs r0._, r3.x
    dp3 r6.w, r17_abs.xzy, c255.x
  + adds_prev r6.z, -r0.y
    dp3 r6.y, r6_abs.xzy, c255.x
    dp3 r6.z, r16_abs.xzy, c255.x
    dp3 r6.x, r15_abs.xzy, c255.x
    sgt r0.x, r6.z, r6.x
    exec    // PredicateClean=false
    max r4.xy, r6.wz, r6.yx
    min r4.xy, r4.wz, r4.xy
  + setp_ne r0._, r0.x
    (!p0) movs r0.x, r4.x
    (p0) rcp r0.x, r6.z
    (p0) mul r0.x, r6.x, r0.x
    (p0) mul r0.x, r0.x, r4.x
    exec
    add r16.x, r9.y, r12.y
    add r16.y, r13.y, r10.y
    add r16.z, r7.y, r11.y
    add r15.x, r9.z, r12.z
    add r15.y, r13.z, r10.z
    add r15.z, r7.z, r11.z
    exec
    add r15.w, r8.z, r1.z
    add r17.x, r9.x, r12.x
    add r17.y, r13.x, r10.x
    add r17.z, r7.x, r11.x
  + rcp r18.x, r6.x
    add r17.w, r8.x, r1.x
  + rcp r18.y, r6.y
    sgt r19.xyz, r6.wxy, r6.yzw
  + rcp r18.z, r6.w
    exec
    mul r6.xyz, r6.yzw, r18.zxy
  + movs r4.z, r4.y
    add r18, r15, r17
  + movs r0._, r8.y
    mul r6.xyz, r6.xyz, r4.yxy
  + adds_prev r16.w, r1.y
    add r18, r18, r16
  + addsc r19.w, c255.z, r0.x
    cndeq r4.xyz, r19.xyz, r4.zxy, r6.xyz
    mad r18, r18, c255.w, c4.x
    exec
    mul r19.xyz, r5.zxy, r0.x
  + rcp r5.x, r18.x
    mul r6.xyz, r14.zxy, r4.x
  + rcp r5.y, r18.w
    dp3 r6.w, r4.zyx, c255.x
  + rcp r5.z, r18.z
    add r6, r19.yxzw, r6.yxzw
  + rcp r5.w, r18.y
    mul r5, r5, c1.x
  + rcp r0.x, r6.w
    mad r2.xyz, r2.xzy, r4.y, r6.xyz
    exec
    mad r2.xyz, r3.xzy, r4.z, r2.xyz
    mad r0.yzw, r0.yywz, c255.z, r2.xxyz
    mul r0.yzw, r0.yywz, r0.x
    add r9.xyz, -r0.ywz, r9.xyz
    add r6.xyz, -r0.ywz, r12.xyz
  + movs r0._, -r0.y
    add r4.xyz, -r0.ywz, r10.xyz
  + adds_prev r10.x, r13.x
    exec
    add r8.xyz, -r0.ywz, r8.xyz
  + movs r0._, -r0.w
    add r3.xyz, -r0.ywz, r1.xyz
  + adds_prev r10.y, r13.y
    add r2.xyz, -r0.yzw, r7.xzy
  + movs r0._, -r0.z
    add r1.xyw, -r0.yzw, r11.xzy
  + adds_prev r10.z, r13.z
    add r3.xyz, r8_abs.xzy, r3_abs.xzy
  + movs r0._, r2_abs.x
    add r4.xyz, r10_abs.xzy, r4_abs.xzy
  + adds_prev r2.x, r1_abs.x
    exec
    add r6.xyz, r9_abs.xzy, r6_abs.xzy
  + movs r0._, r2_abs.y
    dp3 r1.x, r6.zxy, c255.x
  + adds_prev r2.y, r1_abs.y
    dp3 r1.y, r4.zxy, c255.x
  + movs r0._, r2_abs.z
    dp3 r1.z, r3.zxy, c255.x
  + adds_prev r2.z, r1_abs.w
    dp3 r1.w, r2.zxy, c255.x
    mad r1, r5.xwzy, r1.xywz, c0.x
    exec
    max r1, r1.xwyz, c3.x
    min r2, r1.xwyz, c2.x
    dp4 r1.x, r17.yzxw, r2.wyxz
    dp4 r1.y, r16.yzxw, r2.wyxz
    dp4 r1.z, r15.yzxw, r2.wyxz
    dp4 r0.x, r2.wyxz, c255.x
    exece
    mad r0.x, r0.x, c255.y, c255.x
    add r0.yzw, r1.xxyz, r0.yywz
  + rcp r0.x, r0.x
    mul oC0.xyz1, r0.ywz, r0.x

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD PSHQ4x[] =
{
    0x102a1100, 0x000001cc, 0x00000484, 0x00000000, 0x00000024, 0x00000168, 
    0x00000190, 0x00000000, 0x00000000, 0x00000140, 0x0000001c, 0x00000133, 
    0xffff0300, 0x00000006, 0x0000001c, 0x00000000, 0x0000012c, 0x00000094, 
    0x00030000, 0x00010000, 0x0000009c, 0x00000000, 0x000000ac, 0x00020001, 
    0x00010000, 0x000000b0, 0x000000c0, 0x000000d0, 0x00020004, 0x00010000, 
    0x000000b0, 0x000000d8, 0x000000e8, 0x00020002, 0x00010000, 0x000000b0, 
    0x000000f0, 0x00000100, 0x00020003, 0x00010000, 0x000000b0, 0x00000108, 
    0x00000118, 0x00020000, 0x00010000, 0x000000b0, 0x0000011c, 0x24646563, 
    0x616c00ab, 0x0004000c, 0x00010001, 0x00010000, 0x00000000, 0x6b00abab, 
    0x00000003, 0x00010001, 0x00010000, 0x00000000, 0xbf8ccccd, 0x00000000, 
    0x00000000, 0x00000000, 0x6c756d5f, 0x61646400, 0x3ea8f5c3, 0x00000000, 
    0x00000000, 0x00000000, 0x6d61785f, 0x7700abab, 0x3f400000, 0x00000000, 
    0x00000000, 0x00000000, 0x6d696e5f, 0x7700abab, 0x3cf5c28f, 0x00000000, 
    0x00000000, 0x00000000, 0x6d7800ab, 0x3f800000, 0x00000000, 0x00000000, 
    0x00000000, 0x70735f33, 0x5f300032, 0x2e302e32, 0x30333533, 0x2e3000ab, 
    0x00000000, 0x00000001, 0x00000000, 0x00000000, 0x00000014, 0x01fc0010, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000040, 0x00000444, 
    0x10001300, 0x00000004, 0x00000000, 0x000068e7, 0x007f007f, 0x00000001, 
    0x00003050, 0x0000f151, 0x0000f252, 0x0000f353, 0x0000f454, 0x0000f555, 
    0x0000f656, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x3f800000, 0x40000000, 0x3a83126f, 0x3e000000, 0x05556008, 
    0x600e1200, 0x12000555, 0x00011014, 0x00001200, 0xc4000000, 0x00006015, 
    0x601b1200, 0x12000000, 0x00006021, 0x60271000, 0x12000000, 0x0000602d, 
    0x60331200, 0x12000000, 0x00006039, 0x603f1200, 0x12000000, 0x00006045, 
    0x604b1200, 0x12000000, 0x00006051, 0x30571200, 0x22000000, 0xb8087021, 
    0x1f1ffe50, 0x00004000, 0xb808d041, 0x1f1ffe50, 0x00004000, 0xb808b061, 
    0x1f1ffe50, 0x00004000, 0xb808a081, 0x1f1ffe50, 0x00004000, 0x10089021, 
    0x1f1ffe50, 0x00004000, 0x1008c061, 0x1f1ffe50, 0x00004000, 0x10088041, 
    0x1f1ffe50, 0x00004000, 0x10081081, 0x1f1ffe50, 0x00004000, 0xb808e0a1, 
    0x1f1ffe88, 0x00004000, 0xb80830c1, 0x1f1ffe88, 0x00004000, 0x100850a1, 
    0x1f1ffe88, 0x00004000, 0x100820c1, 0x1f1ffe88, 0x00004000, 0x10080001, 
    0x1f1ff447, 0x00004000, 0xc807000f, 0x0262b700, 0xe0020000, 0xc8070010, 
    0x0262b700, 0xe0050000, 0x14070011, 0x0262b7c6, 0xe00e0003, 0x041b0604, 
    0x0365651b, 0xe0080100, 0x140e0006, 0x024141b1, 0xe0090c03, 0x04240604, 
    0x01c96cc6, 0xb086ff00, 0x14080004, 0x00b86c6c, 0xb084ff03, 0x04480606, 
    0x01b46cb1, 0xb091ff00, 0xc8020006, 0x00b46c00, 0xb086ff00, 0xc8040006, 
    0x00b46c00, 0xb090ff00, 0xc8010006, 0x00b46c00, 0xb08fff00, 0xc8010000, 
    0x00c66c00, 0xe5060600, 0xc8030004, 0x00c76d00, 0xe2060600, 0x70030004, 
    0x00c7b06c, 0xe3040400, 0x14100000, 0x1000006c, 0xe2000004, 0x4c100000, 
    0x180000c6, 0xe2000006, 0xc8010000, 0x186c6c00, 0xe1060000, 0xc8010000, 
    0x186c6c00, 0xe1000400, 0xc8010010, 0x00b1b100, 0xe0090c00, 0xc8020010, 
    0x00b1b100, 0xe00d0a00, 0xc8040010, 0x00b1b100, 0xe0070b00, 0xc801000f, 
    0x00c6c600, 0xe0090c00, 0xc802000f, 0x00c6c600, 0xe00d0a00, 0xc804000f, 
    0x00c6c600, 0xe0070b00, 0xc808000f, 0x00c6c600, 0xe0080100, 0xc8010011, 
    0x006c6c00, 0xe0090c00, 0xc8020011, 0x006c6c00, 0xe00d0a00, 0x4c141211, 
    0x006c6c6c, 0xe0070b06, 0x4c281211, 0x006c6cb1, 0xe0080106, 0x4c471213, 
    0x00bf151b, 0xe5060606, 0x14470406, 0x0015beb1, 0xe1061204, 0x140f0012, 
    0x000000b1, 0xe00f1108, 0x04871006, 0x00c0bdb1, 0xe1060401, 0xb08f1312, 
    0x000000c0, 0xc01210ff, 0xc8070004, 0x00c0bec0, 0xec130406, 0xc80f0012, 
    0x00001b6c, 0x8b12ff04, 0x4c170513, 0x00be6c6c, 0xe1050012, 0x4c270506, 
    0x00be6c1b, 0xe10e0412, 0x4c480506, 0x00626cc6, 0xb004ff12, 0x4c8f0506, 
    0x000d0db1, 0xe0130612, 0x4c1f0005, 0x00006c1b, 0xa1050106, 0xc8070002, 
    0x00b4b1c0, 0xeb020406, 0xc8070002, 0x00b4c6c0, 0xeb030402, 0xc80e0000, 
    0x00d1c6fc, 0xab00ff02, 0xc80e0000, 0x00d16c00, 0xe1000000, 0xc8070009, 
    0x04c9c000, 0xe0000900, 0x14070006, 0x05c9c0b1, 0xe0000c00, 0x04170a04, 
    0x04c9c06c, 0xe0000a0d, 0x14070008, 0x05c9c01b, 0xe0000800, 0x04270a03, 
    0x04c9c0b1, 0xe000010d, 0x14070002, 0x0515b4c6, 0xe0000700, 0x044b0a01, 
    0x0415b4c6, 0xe0000b0d, 0x14070003, 0x00b4b46c, 0xe0888382, 0x04170204, 
    0x00b4b46c, 0xe08a8481, 0x14070006, 0x00b4b4b1, 0xe0898682, 0x04210201, 
    0x00be6cb1, 0xb006ff81, 0x14020001, 0x00be6cc6, 0xb004ff82, 0x04440201, 
    0x00be6c1b, 0xb003ff81, 0xc8080001, 0x00be6c00, 0xb002ff00, 0xc80f0001, 
    0x0088d06c, 0xcb050100, 0xc80f0001, 0x00f86c00, 0xa2010300, 0xc80f0002, 
    0x00f86c00, 0xa3010200, 0xc8010001, 0x0025e300, 0xef110200, 0xc8020001, 
    0x0025e300, 0xef100200, 0xc8040001, 0x0025e300, 0xef0f0200, 0xc8010000, 
    0x00e36c00, 0xaf02ff00, 0xc8010000, 0x006cb16c, 0x8b00ffff, 0x4c1e0000, 
    0x00fcd16c, 0xe0010000, 0xc88fc000, 0x00c96c00, 0xe1000000, 0x00000000, 
    0x00000000, 0x00000000
};
