#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh simple.vs.h /Tvs_3_0 filters\normal.cg /Emain_vertex /VnVSSimple
//
//
// Parameters:
//
//   float4x4 modelViewProj;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   modelViewProj c0       4
//

// Shader type: vertex 

xvs_3_0
defconst modelViewProj, float, matrix_columns, [4, 4], c0-3
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=2
config VsResource=1

dcl_index r0.x
dcl_texcoord o0.xy


    exec
    vfetch r2, r0.x, position
    vfetch r0.xy__, r0.x, texcoord
    alloc position
    exec
    mul r1, r2.w, c3.xwzy
    mad r1, r2.z, c2.xwzy, r1
    mad r1, r2.y, c1.xzyw, r1.xzwy
    mad oPos, r2.x, c0, r1.xzyw
    alloc interpolators
    exece
    mov o0.xy, r0.xy

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD VSSimple[] =
{
    0x102a1101, 0x000000c4, 0x00000084, 0x00000000, 0x00000024, 0x00000000, 
    0x0000008c, 0x00000000, 0x00000000, 0x00000064, 0x0000001c, 0x00000057, 
    0xfffe0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000050, 0x00000030, 
    0x00020000, 0x00040000, 0x00000040, 0x00000000, 0x6d6f6465, 0x6c566965, 
    0x7750726f, 0x6a00abab, 0x00030003, 0x00040004, 0x00010000, 0x00000000, 
    0x76735f33, 0x5f300032, 0x2e302e32, 0x30333533, 0x2e3000ab, 0x00000000, 
    0x00000084, 0x00010002, 0x00000000, 0x00000000, 0x00000821, 0x00000001, 
    0x00000002, 0x00000001, 0x00000290, 0x00100003, 0x00305004, 0x00003050, 
    0x00001009, 0x30052003, 0x00001200, 0xc2000000, 0x00004005, 0x00001200, 
    0xc4000000, 0x00001009, 0x00002200, 0x00000000, 0x05f82000, 0x00000688, 
    0x00000000, 0x05f80000, 0x00000fc8, 0x00000000, 0xc80f0001, 0x001b8800, 
    0xa1020300, 0xc80f0001, 0x00c68800, 0xab020201, 0xc80f0001, 0x00b13494, 
    0xab020101, 0xc80f803e, 0x006c0034, 0xab020001, 0xc8038000, 0x00b0b000, 
    0xe2000000, 0x00000000, 0x00000000, 0x00000000
};
