#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh simple.ps.h /Tps_3_0 filters\normal.cg /Emain_fragment /VnPSSimple
//
//
// Parameters:
//
//   sampler2D decal;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   decal        s0       1
//

// Shader type: pixel 

xps_3_0
defconst decal, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0.xy


    exec
    tfetch2D r0.xyz_, r0.xy, tf0
    alloc colors
    exece
    mov oC0.xyz1, r0.xyz

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD PSSimple[] =
{
    0x102a1100, 0x000000a8, 0x0000003c, 0x00000000, 0x00000024, 0x00000000, 
    0x00000084, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00030000, 0x00010000, 0x00000038, 0x00000000, 0x64656361, 0x6c00abab, 
    0x0004000c, 0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e32, 0x30333533, 0x2e3000ab, 0x00000000, 0x0000003c, 0x10000000, 
    0x00000004, 0x00000000, 0x00000821, 0x00010001, 0x00000001, 0x00003050, 
    0x00011002, 0x00001200, 0xc4000000, 0x00001003, 0x00002200, 0x00000000, 
    0x10080001, 0x1f1ffe88, 0x00004000, 0xc88fc000, 0x00c0c000, 0xe2000000, 
    0x00000000, 0x00000000, 0x00000000
};
