#if 0
//
// Generated by 2.0.20675.0
//
//   fxc /Fh vs.h /Tvs_3_0 libwiigui.hlsl /EVSmain
//
//
// Parameters:
//
//   float4x4 matWVP;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   matWVP       c0       4
//

// Shader type: vertex 

xvs_3_0
defconst matWVP, float, matrix_columns, [4, 4], c0-3
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=3
config VsResource=1
// VsExportCount=1

dcl_index r0.x
dcl_texcoord o0.xy
dcl_color o1


    exec
    vfetch r3, r0.x, position
    vfetch r1, r0.x, color
    vfetch r0.xy__, r0.x, texcoord
    alloc position
    exec
    mul r2, r3.z, c2.xzwy
    mad r2, r3.y, c1.xzwy, r2
    mad r2, r3.x, c0.xzwy, r2
    mad oPos.xzw, r3.w, c3.xzzw, r2.xyyz
    mad oPos.y, -r3.w, c3.y, -r2.w
    alloc interpolators
    exece
    mov o0.xy, r0.xy
    mov o1, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_VSmain[] =
{
    0x102a1101, 0x000000c8, 0x000000a8, 0x00000000, 0x00000024, 0x00000000, 
    0x00000084, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xfffe0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00020000, 0x00040000, 0x00000038, 0x00000000, 0x6d617457, 0x565000ab, 
    0x00030003, 0x00040004, 0x00010000, 0x00000000, 0x76735f33, 0x5f300032, 
    0x2e302e32, 0x30363735, 0x2e3000ab, 0x00000000, 0x000000a8, 0x00110003, 
    0x00000000, 0x00000000, 0x00001842, 0x00000001, 0x00000003, 0x00000002, 
    0x00000290, 0x00100003, 0x0000a004, 0x00305005, 0x00003050, 0x0001f1a0, 
    0x0000100b, 0x0000100c, 0x70153003, 0x00001200, 0xc2000000, 0x00005006, 
    0x00001200, 0xc4000000, 0x0000200b, 0x00002200, 0x00000000, 0x05f83000, 
    0x00000688, 0x00000000, 0x05f81000, 0x00000688, 0x00000000, 0x05f80000, 
    0x00000fc8, 0x00000000, 0xc80f0002, 0x00c69400, 0xa1030200, 0xc80f0002, 
    0x00b19400, 0xab030102, 0xc80f0002, 0x006c9400, 0xab030002, 0xc80d803e, 
    0x001b04f0, 0xab030302, 0xc802803e, 0x051bb11b, 0xab030302, 0xc8038000, 
    0x00b0b000, 0xe2000000, 0xc80f8001, 0x00000000, 0xe2010100, 0x00000000, 
    0x00000000, 0x00000000
};
